on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

name: Build and release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # following 2 are github suggested caching for yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install
        run: yarn install
      - name: build
        run: yarn build


      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
      - name: Add to IPFS
        id: ipfs
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4 
        with:
          pin-name: 'theboard'
          path: './dist'
          pinata-api-key: ${{ secrets.PINATAAPIKEY }}
          pinata-secret-api-key: ${{ secrets.PINATASECRETAPIKEY }}
          verbose: true
          remove-old: true
      - name: Make release dir
        run: mkdir release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: './release/the-board-files.zip'
          path: dist
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'tar'
          filename: './release/the-board-files.tar.gz'
          path: dist
            
      - name: Add CID to release
        run: 'echo ${{ steps.ipfs.outputs.HASH }} > ./release/ipfs.cid'

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "release/"
          tag: ${{ github.ref }}

